name = "acdatservice"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-09"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[r2_buckets]]
binding = 'DATS_BUCKET'
bucket_name = 'treestats-acdats'

[[d1_databases]]
binding = "DATS_DB"
database_name = "dats"
database_id = "21ee3b5f-a28f-43e3-9def-b29f74c6c7ac"

[observability]
enabled = true
